### ISSUE TITLE
网盘链接不存在，求更新

### ISSUE THREAD

**Issue by iiwerid** [hanc00l/wooyun_public#10]

**Comment by hanc00l** [comment]
已更新：http://pan.baidu.com/s/1kVdJuNd,提取密码hn9d

**Comment by hanc00l** [comment]
有数据的虚拟机1刚测试了可以下载，你试试看。没有数据的虚拟机已没有意义了，如果要自行搭建环境，可以参看install.md。

**Comment by iiwerid** [comment]
谢谢大神哈 O(∩_∩)O哈哈~
