### ISSUE TITLE
新上传的少了part02.rar

### ISSUE THREAD

**Issue by ff00x0** [hanc00l/wooyun_public#2]
请大牛看看 少了一个文件

**Comment by hanc00l** [comment]
part2有点问题，正在重传中，昨天上传中一直不断出现“网络异常”，传输中断要手工重点一下才能继续，百度云盘坑爹呀。

**Comment by hanc00l** [comment]
part2有点问题，正在重传中，昨天上传中一直不断出现“网络异常”，传输中断要手工重点一下才能继续，百度云盘坑爹呀。快传完的时候百度云的虚拟机挂掉了，等传完我校验的时候发现part2的md5值不对。只有又重新传part2，还花了27块钱买了一个月的SVIP，泪奔。。。

**Comment by hanc00l** [comment]
part2有点问题，正在重传中，昨天上传中一直不断出现“网络异常”，传输中断要手工重点一下才能继续，百度云盘坑爹呀。快传完的时候百度云的虚拟机挂掉了，等传完我校验的时候发现part2的md5值不对。只有又重新传part2，还花了27块钱买了一个月的SVIP，泪奔。。。

**Comment by hanc00l** [comment]
part2有点问题，正在重传中，昨天上传中一直不断出现“网络异常”，传输中断要手工重点一下才能继续，百度云盘坑爹呀。快传完的时候百度云的虚拟机挂掉了，等传完我校验的时候发现part2的md5值不对。只有又重新传part2，还花了27块钱买了一个月的SVIP，泪奔。。。

**Comment by ff00x0** [comment]
谢谢大牛的无私分享
