### ISSUE TITLE
中文的全文搜索好像有问题

### ISSUE THREAD

**Issue by cyberwangw** [hanc00l/wooyun_public#3]
我输中文全文搜索查公开漏洞页面就卡住了，app.py的命令行里只收到“GET /  HTTP……”的请求，大牛求解

**Comment by hanc00l** [comment]
全文搜索有点慢哦，搜索算法用的最简单和原始的方法，如果经常进行全文搜索，建议重新优化一下算法。

han2008@qq.com

**Comment by cyberwangw** [comment]
好的，感谢大牛分享

**Comment by hanc00l** [comment]
要提供全文搜索效率，还是得用elasticsearch，可以一起研究研究。

han2008@qq.com

**Comment by CaledoniaProject** [comment]
可以用 ensureIndex 加一个 TEXT 索引试试，至少前缀搜索不会卡

**Comment by CaledoniaProject** [comment]
换 ES 的话用 nGram 做一个索引就可以了
