### ISSUE TITLE
mongodb数据库

### ISSUE THREAD

**Issue by paulpiercezxy** [hanc00l/wooyun_public#31]
不好意思，请问可以单独上传一份mongo数据库文件吗，那个镜像文件也是解压crc出错，但是可以运行。想把数据库文件导出来，但是连接不上，无法删除mongod.lock,提示read-only file system,google了大半天也没有解决。。

**Comment by hanc00l** [comment]
可以的，晚上我回去把mongodb导出后上传到网上给你。

**Comment by paulpiercezxy** [comment]
嗯，谢谢大牛！

**Comment by hanc00l** [comment]
mongodb的数据库dump的下载地址-> 链接：http://pan.baidu.com/s/1bpmPLtd 密码：6x6v
解压后，使用mongorestore恢复完整的库。
