### ISSUE TITLE
请问 有考虑出docker版本吗?

### ISSUE THREAD

**Issue by jev001** [hanc00l/wooyun_public#44]
在使用过程中, 发现整体依托于虚拟机有点庞大,随想了解下有制作docker版本的计划吗?

**Comment by hanc00l** [comment]
暂时没有，“庞大”主要是因为离线的图片资源

**Comment by jev001** [comment]
好的,分离数据呢？以前看 有drops2 分离出来了 bugs 里面的可以分离出来吗?
