### ISSUE TITLE
mongodb 全文查询太慢

### ISSUE THREAD

**Issue by RicterZ** [hanc00l/wooyun_public#6]
mysql 才 2s..望改进

**Comment by hanc00l** [comment]
正在改为用elasticsearch搜索，非常快

han2008@qq.com

**Comment by RicterZ** [comment]
thx，另外希望改用 docker（。
因为 vmware 为收费软件，然而我已用 Parallels Desktop，不太想买了..

**Comment by wooutl** [comment]
期待有漏洞全的版本，我记得之前你写了。。。

**Comment by hanc00l** [comment]
希望乌云早日重新开放，就不用这样麻烦了；欢迎各位高手和hacker共同完善。

**Comment by hanc00l** [comment]
mongodb进行全文搜索的确是太慢，目前正在改为全文搜索使用elasticsearch。搭建elasticsearch步骤比较麻烦，已解决，程序修改差不多了；现在唯一就是全文搜索的中文分词问题， 经过反复测试，使用了IK插件，但分词效果不理想。不知道是不是我哪里搞得不对，还望有高手指点指点。

**Comment by 1c3z** [comment]
sudo　apt-get install silversearcher-ag

ag --html 关键字

第一次久点，后面只需要3s，机械硬盘，亲测。

**Comment by RicterZ** [comment]
@1c3z ag 起来并不是很直观..
