### ISSUE TITLE
第二个虚拟机 git pull 后不能用，应该是需要commit吧

### ISSUE THREAD

**Issue by KnightUK** [hanc00l/wooyun_public#7]

**Comment by hanc00l** [comment]
git reset --hard origin/master #返回到某个节点，不保留修改。或者把merge有冲突的文件删除掉重新pull也可以。这个虚拟机是去年最10月时候装的，一直没有更新过了。

**Comment by KnightUK** [comment]
wooyun_public目录下没有wooyun和wooyun_drops目录，unknown command crawl，是不是我没用对啊。 你这个爬虫太厉害了，这样不是可以爬取整个网站了？

**Comment by hanc00l** [comment]
或者你把wooyun_public删掉，重新git pull吧。
现在wooyun已经关了，没法爬了。

**Comment by KnightUK** [comment]
wooyun升级还是长期关闭？算了，我就用第一个虚拟机玩玩吧，谢谢指导
